/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.EcoSystem;
import model.Network;
import model.UserAccount;

/**
 *
 * @author DELL
 */
public class LoginJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private EcoSystem system;
    private Network network;

    /**
     * Creates new form NewJPanel
     */
    public LoginJPanel(JPanel userProcessContainer, EcoSystem system, Network network) {
        
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.network = network;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogInJPanel = new javax.swing.JPanel();
        lblScreenTitle = new javax.swing.JLabel();
        lblMainTitle = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        lblScreenTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        lblScreenTitle.setText("Disaster Response System");

        lblMainTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblMainTitle.setText("Log In");

        lblUser.setText("UserName");

        lblPass.setText("Password");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LogInJPanelLayout = new javax.swing.GroupLayout(LogInJPanel);
        LogInJPanel.setLayout(LogInJPanelLayout);
        LogInJPanelLayout.setHorizontalGroup(
            LogInJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogInJPanelLayout.createSequentialGroup()
                .addGroup(LogInJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LogInJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblScreenTitle))
                    .addGroup(LogInJPanelLayout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(lblMainTitle))
                    .addGroup(LogInJPanelLayout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addGroup(LogInJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUser)
                            .addComponent(lblPass))
                        .addGap(86, 86, 86)
                        .addGroup(LogInJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUser)
                            .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)))
                    .addGroup(LogInJPanelLayout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(btnSubmit)))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        LogInJPanelLayout.setVerticalGroup(
            LogInJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogInJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblScreenTitle)
                .addGap(49, 49, 49)
                .addComponent(lblMainTitle)
                .addGap(45, 45, 45)
                .addGroup(LogInJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUser)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(LogInJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPass)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(btnSubmit)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        add(LogInJPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        loginAction();
    }//GEN-LAST:event_btnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LogInJPanel;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel lblMainTitle;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblScreenTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

    private void loginAction() {
        
        String username = txtUser.getText().trim();
        String password = txtPass.getText().trim();

        UserAccount account = system.authenticateUser(username, password);

        if (account == null) {
            JOptionPane.showMessageDialog(this, "Invalid username or password.");
            return;
        }

        JPanel workArea = account.getRole().createWorkArea(userProcessContainer, account, network);
        userProcessContainer.add("WorkArea", workArea);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }
}
