/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import java.awt.CardLayout;
import javax.swing.JPanel;
import config.ConfigureSystem;
import model.EcoSystem;

/**
 *
 * @author sashajohnson
 */
public class MainJFrame extends javax.swing.JFrame {
    private EcoSystem system;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainJFrame.class.getName());
    
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        system = ConfigureSystem.configure();
        initComponents();
        setSize(700, 460);
        setLocationRelativeTo(null);
        
        LoginJPanel loginPanel = new LoginJPanel(mainContainerPanel, system);
        mainContainerPanel.add("LoginJPanel", loginPanel);

        ((CardLayout) mainContainerPanel.getLayout())
                .show(mainContainerPanel, "LoginJPanel");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainContainerPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        mainContainerPanel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        mainContainerPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(mainContainerPanel, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainJFrame().setVisible(true));
    }
    public JPanel getMainContainer() {
        return mainContainerPanel;
    }

    public EcoSystem getSystem() {
        return system;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainContainerPanel;
    // End of variables declaration//GEN-END:variables
}
