/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.admin;

import java.awt.CardLayout;
import javax.swing.JPanel;
import model.UserAccount;

/**
 *
 * @author sashajohnson
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private UserAccount account;
    /**
     * Creates new form AdminWorkAreaJPanel
     */
    public AdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount account) {
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUsers = new javax.swing.JButton();
        btnEnterprises = new javax.swing.JButton();
        btnOrganizations = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblScreenTitle = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        btnManageReports = new javax.swing.JButton();

        btnUsers.setBackground(new java.awt.Color(102, 153, 255));
        btnUsers.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnUsers.setForeground(new java.awt.Color(255, 255, 255));
        btnUsers.setText("Manage Users");
        btnUsers.setBorderPainted(false);
        btnUsers.setOpaque(true);
        btnUsers.addActionListener(this::btnUsersActionPerformed);

        btnEnterprises.setBackground(new java.awt.Color(102, 153, 255));
        btnEnterprises.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnEnterprises.setForeground(new java.awt.Color(255, 255, 255));
        btnEnterprises.setText("Manage Enterprises");
        btnEnterprises.setBorderPainted(false);
        btnEnterprises.setOpaque(true);
        btnEnterprises.addActionListener(this::btnEnterprisesActionPerformed);

        btnOrganizations.setBackground(new java.awt.Color(102, 153, 255));
        btnOrganizations.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnOrganizations.setForeground(new java.awt.Color(255, 255, 255));
        btnOrganizations.setText("Manage Organizations");
        btnOrganizations.setBorderPainted(false);
        btnOrganizations.setOpaque(true);
        btnOrganizations.addActionListener(this::btnOrganizationsActionPerformed);

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setText("Admin Dashboard");

        lblScreenTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        lblScreenTitle.setText("Disaster Response System");

        btnLogOut.setBackground(new java.awt.Color(153, 153, 153));
        btnLogOut.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOut.setText("Log out");
        btnLogOut.setBorderPainted(false);
        btnLogOut.setOpaque(true);
        btnLogOut.addActionListener(this::btnLogOutActionPerformed);

        btnManageReports.setBackground(new java.awt.Color(102, 153, 255));
        btnManageReports.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnManageReports.setForeground(new java.awt.Color(255, 255, 255));
        btnManageReports.setText("Manage Reports");
        btnManageReports.setBorderPainted(false);
        btnManageReports.setOpaque(true);
        btnManageReports.addActionListener(this::btnManageReportsActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblScreenTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(lblTitle)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                .addComponent(btnLogOut)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOrganizations, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnterprises, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageReports, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblScreenTitle)
                    .addComponent(btnLogOut))
                .addGap(51, 51, 51)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(btnOrganizations, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnEnterprises, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnManageReports, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsersActionPerformed
        // TODO add your handling code here:
        ManageUsersJPanel panel = new ManageUsersJPanel (userProcessContainer, account);
        userProcessContainer.add("ManageUsersJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnUsersActionPerformed

    private void btnEnterprisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterprisesActionPerformed
        // TODO add your handling code here:
        ManageEnterprisesJPanel panel = new ManageEnterprisesJPanel (userProcessContainer, account);
        userProcessContainer.add("ManageEnterprisesJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnEnterprisesActionPerformed

    private void btnOrganizationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrganizationsActionPerformed
        // TODO add your handling code here:
        ManageOrganizationsJPanel panel = new ManageOrganizationsJPanel (userProcessContainer, account);
        userProcessContainer.add("ManageOrganizationsJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnOrganizationsActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnManageReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageReportsActionPerformed
        // TODO add your handling code here:
        ReportingJPanel panel = new ReportingJPanel (userProcessContainer, account);
        userProcessContainer.add("ReportingJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageReportsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnterprises;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnManageReports;
    private javax.swing.JButton btnOrganizations;
    private javax.swing.JButton btnUsers;
    private javax.swing.JLabel lblScreenTitle;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
