package ui.admin;

import java.awt.CardLayout;
import javax.swing.JPanel;
import model.EcoSystem;
import model.UserAccount;
import ui.requests.ReportJPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author sashajohnson
 */
public class ReportingJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private UserAccount account;
    private EcoSystem system;
    /**
     * Creates new form ReportingJPanel
     */
    public ReportingJPanel(JPanel userProcessContainer, UserAccount account) {
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.system = EcoSystem.getInstance();
        initComponents();
        setupTable(); 
        populateSummary();
        populateTable();
    }
    
    private void setupTable() {
        tblReports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Request ID",
                "Type",
                "Sender",
                "Status",
                "Priority",
                "Organization"
            }
        ));
        }

        private model.WorkRequest getSelectedRequest() {
            int selectedRow = tblReports.getSelectedRow();

            if (selectedRow < 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Please select a request first.");
                return null;
            }

            String requestId = String.valueOf(tblReports.getValueAt(selectedRow, 0));

            for (model.enterprise.Enterprise enterprise : system.getNetwork().getEnterpriseList()) {
                for (model.organization.Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    for (model.WorkRequest request : org.getWorkQueue().getWorkRequestList()) {
                        if (requestId.equals(request.getRequestId())) {
                            return request;
                        }
                    }
                }
        }

        return null;
    }
    public void refreshTable() {
        populateSummary();
        populateTable();
    }
    private void populateSummary() {
        int total = 0;
        int pending = 0;
        int inProgress = 0;
        int completed = 0;

        for (model.enterprise.Enterprise enterprise : system.getNetwork().getEnterpriseList()) {
            for (model.organization.Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
                for (model.WorkRequest request : org.getWorkQueue().getWorkRequestList()) {
                    total++;

                    if ("Pending".equalsIgnoreCase(request.getStatus())) {
                        pending++;
                    } else if ("In Progress".equalsIgnoreCase(request.getStatus())) {
                        inProgress++;
                    } else if ("Completed".equalsIgnoreCase(request.getStatus())) {
                        completed++;
                    }
                }
            }
        }

        lblTotalRequestsValue.setText(String.valueOf(total));
        lblPendingValue.setText(String.valueOf(pending));
        lblInProgressValue.setText(String.valueOf(inProgress));
        lblCompletedValue.setText(String.valueOf(completed));
    }
    
    private void populateTable() {
        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) tblReports.getModel();

    model.setRowCount(0);

    for (model.enterprise.Enterprise enterprise : system.getNetwork().getEnterpriseList()) {
        for (model.organization.Organization org :
                enterprise.getOrganizationDirectory().getOrganizationList()) {

            for (model.WorkRequest request :
                    org.getWorkQueue().getWorkRequestList()) {

                Object[] row = new Object[6];

                row[0] = request.getRequestId();
                row[1] = request.getClass().getSimpleName();
                row[2] = request.getSender() != null
                        ? request.getSender().getUsername()
                        : "";

                row[3] = request.getStatus();
                row[4] = request.getPriority();
                row[5] = org.getName();

                model.addRow(row);
            }
        }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblScreenTitle = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblTotalRequestsValue = new javax.swing.JLabel();
        lblPendingValue = new javax.swing.JLabel();
        lblInProgressValue = new javax.swing.JLabel();
        lblCompletedValue = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReports = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        btnBack.setBackground(new java.awt.Color(153, 153, 153));
        btnBack.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("< Back");
        btnBack.setBorderPainted(false);
        btnBack.setOpaque(true);
        btnBack.addActionListener(this::btnBackActionPerformed);

        lblScreenTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        lblScreenTitle.setText("Disaster Response System");

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setText("Report Overview");

        lblTotalRequestsValue.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblTotalRequestsValue.setText("0");

        lblPendingValue.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblPendingValue.setText("0");

        lblInProgressValue.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblInProgressValue.setText("0");

        lblCompletedValue.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblCompletedValue.setText("0");

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel1.setText("Total Requests");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel2.setText("Pending");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel3.setText("In Progress");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel4.setText("Completed");

        tblReports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblReports);

        btnView.setBackground(new java.awt.Color(102, 153, 255));
        btnView.setForeground(new java.awt.Color(255, 255, 255));
        btnView.setText("View");
        btnView.setBorderPainted(false);
        btnView.setOpaque(true);
        btnView.addActionListener(this::btnViewActionPerformed);

        btnUpdate.setBackground(new java.awt.Color(102, 153, 255));
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.setBorderPainted(false);
        btnUpdate.setOpaque(true);
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblScreenTitle)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnBack)
                                .addGap(183, 183, 183)
                                .addComponent(lblTitle))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(lblInProgressValue))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(lblCompletedValue))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(lblPendingValue))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(lblTotalRequestsValue)))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnView)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUpdate))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblScreenTitle)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBack)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotalRequestsValue)
                            .addComponent(jLabel1))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPendingValue)
                            .addComponent(jLabel2))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblInProgressValue)
                            .addComponent(jLabel3))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCompletedValue)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnView)
                    .addComponent(btnUpdate))
                .addContainerGap(92, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        model.WorkRequest selectedRequest = getSelectedRequest();
        if (selectedRequest == null) {
            return;
        }

        ReportJPanel panel = new ReportJPanel(userProcessContainer, account, selectedRequest, ReportJPanel.MODE_VIEW);
        userProcessContainer.add("ReportJPanel_VIEW", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        model.WorkRequest selectedRequest = getSelectedRequest();
        if (selectedRequest == null) {
            return;
        }

        ReportJPanel panel = new ReportJPanel(userProcessContainer, account, selectedRequest, ReportJPanel.MODE_UPDATE);
        userProcessContainer.add("ReportJPanel_UPDATE", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCompletedValue;
    private javax.swing.JLabel lblInProgressValue;
    private javax.swing.JLabel lblPendingValue;
    private javax.swing.JLabel lblScreenTitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalRequestsValue;
    private javax.swing.JTable tblReports;
    // End of variables declaration//GEN-END:variables
}
