/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.fire;

import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.UserAccount;
import model.WorkRequest;
import model.organization.Organization;

/**
 *
 * @author DELL
 */
public class ProcessRequestsJPanel extends javax.swing.JPanel {
    
     private JPanel userProcessContainer;
    private UserAccount account;
    private Organization org;

    /**
     * Creates new form ProcessRequestsJPanel
     */
    public ProcessRequestsJPanel(JPanel userProcessContainer, UserAccount account, Organization org) {
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.org = org;
        initComponents();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblScreenTitle = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequest = new javax.swing.JTable();
        lblRescue = new javax.swing.JLabel();
        BtnAssign = new javax.swing.JButton();
        BtnInProgress = new javax.swing.JButton();
        btnResolved = new javax.swing.JButton();
        txtNotesArea = new javax.swing.JScrollPane();
        txtNotes = new javax.swing.JTextArea();

        lblScreenTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        lblScreenTitle.setText("Disaster Response System");

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setText("Process Requests");

        btnBack.setBackground(new java.awt.Color(153, 153, 153));
        btnBack.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("< Back");
        btnBack.setBorderPainted(false);
        btnBack.setOpaque(true);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Sender", "Location", "Message", "Status", "Assigned"
            }
        ));
        jScrollPane1.setViewportView(tblRequest);

        lblRescue.setText("Rescue Action:");

        BtnAssign.setText("Assign To Me");
        BtnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAssignActionPerformed(evt);
            }
        });

        BtnInProgress.setText("In Progress");
        BtnInProgress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInProgressActionPerformed(evt);
            }
        });

        btnResolved.setText("Resolved");
        btnResolved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResolvedActionPerformed(evt);
            }
        });

        txtNotes.setColumns(20);
        txtNotes.setRows(5);
        txtNotesArea.setViewportView(txtNotes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblScreenTitle)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(277, 277, 277)
                                .addComponent(lblTitle))
                            .addComponent(btnBack)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(lblRescue)
                        .addGap(50, 50, 50)
                        .addComponent(txtNotesArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(BtnAssign)
                        .addGap(77, 77, 77)
                        .addComponent(BtnInProgress)
                        .addGap(83, 83, 83)
                        .addComponent(btnResolved)))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblScreenTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRescue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnAssign)
                            .addComponent(BtnInProgress)
                            .addComponent(btnResolved))
                        .addGap(92, 92, 92))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNotesArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void BtnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAssignActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tblRequest.getSelectedRow();
        if (selectedRow < 0) return;

        WorkRequest req = (WorkRequest) tblRequest.getValueAt(selectedRow, 0);
        req.setReceiver(account);
        req.setStatus("Assigned");

        populateTable();
    }//GEN-LAST:event_BtnAssignActionPerformed

    private void BtnInProgressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInProgressActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tblRequest.getSelectedRow();
        if (selectedRow < 0) return;

        WorkRequest req = (WorkRequest) tblRequest.getValueAt(selectedRow, 0);

        if (req.getReceiver() != account) {
            javax.swing.JOptionPane.showMessageDialog(null, "Assign to yourself first");
            return;
        }

        req.setStatus("In Progress");
        populateTable();
    }//GEN-LAST:event_BtnInProgressActionPerformed

    private void btnResolvedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResolvedActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tblRequest.getSelectedRow();
        if (selectedRow < 0) return;

        WorkRequest req = (WorkRequest) tblRequest.getValueAt(selectedRow, 0);

        if (req.getReceiver() != account) {
            javax.swing.JOptionPane.showMessageDialog(null, "Assign to yourself first");
            return;
        }

        req.setMessage(req.getMessage() + " | Action: " + txtNotes.getText());
        req.setStatus("Resolved");
        req.setResolvedDate(new Date());

        populateTable();
    }//GEN-LAST:event_btnResolvedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAssign;
    private javax.swing.JButton BtnInProgress;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnResolved;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRescue;
    private javax.swing.JLabel lblScreenTitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblRequest;
    private javax.swing.JTextArea txtNotes;
    private javax.swing.JScrollPane txtNotesArea;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
       
         DefaultTableModel model = (DefaultTableModel) tblRequest.getModel();
        model.setRowCount(0);

        for (WorkRequest req : org.getWorkQueue().getWorkRequestList()) {
            Object[] row = new Object[6];
            row[0] = req;
            row[1] = req.getSender();
            row[2] = "Location TBD"; // optional if no location field
            row[3] = req.getMessage();
            row[4] = req.getStatus();
            row[5] = req.getReceiver();
            model.addRow(row);
        }
    }
}
